//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public int Id { get; set; }
        public Nullable<int> ParkId { get; set; }
        public string Name { get; set; }
    
        public virtual Park Park { get; set; }
    }
}
