//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int ParkId { get; set; }
        public int SportId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual Park Park { get; set; }
    }
}
