//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public int ParkId { get; set; }
        public Nullable<int> PriceRating { get; set; }
        public Nullable<int> AmentiesRating { get; set; }
        public string CommentText { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Park Park { get; set; }
    }
}
